SELECT JSON_ARRAYAGG(
  JSON_OBJECT(
    'WPL_ID' VALUE WPL.LINE_REC_ID,
    'COLOR' VALUE WP.COLOR,
    'PROFILE_ID' VALUE WPL.PROFILE_ID,
    'START_TIME' VALUE WPL.START_TIME,
    'END_TIME' VALUE WPL.END_TIME
  )
) AS json_data
FROM WORKING_PROFILE_LINES WPL
JOIN WORKING_PROFILE WP ON WPL.PROFILE_ID = WP.PROFILE_ID
WHERE lower(WP.PROFILE_ID) NOT LIKE '%test%'
AND lower(WP.PROFILE_ID) NOT LIKE '%nam%'
AND (WPL.START_DAY = 2 AND WPL.END_DAY = 2 AND WPL.DAY_OF_WEEK = 2)
AND lower(WP.PROFILE_ID) LIKE '%' || LOWER(TRIM(:P43_SEARCH_PROFILE)) || '%';