SELECT JSON_ARRAYAGG(
  JSON_OBJECT(
    'ID' VALUE ID,
    'PROFILE_ID' VALUE PROFILE_ID,
    -- 'START_TIME' VALUE TO_CHAR(START_TIME, 'YYYY-MM-DD'),
    -- 'END_TIME' VALUE TO_CHAR(END_TIME, 'YYYY-MM-DD'),
    'TIMELINE' VALUE STANDARD_TIME,
    'COLOR' VALUE COLOR
  )
) AS json_data
from PROFILE_TIME_LIST;
