
-- < GET PROFILES
-- table: WORKING_PROFILE
BEGIN
    SP_GET_WORKING_SCHEDULE_PROFILE('V01');
END;

-- table: WORKING_PROFILE_DETAIL
BEGIN
    SP_GET_WORKING_SCHEDULE_PROFILE_DETAIL('V01');
END;
-- > GET PROFILES


-- < GET TIMESHEET
-- table: EMP_TIME_SHEET
BEGIN
    -- p_legal_entity_id NVARCHAR2,
    -- p_from_date NVARCHAR2,
    -- P_to_date NVARCHAR2,
    -- P_transffered NVARCHAR2
    SP_GET_TIME_SHEET('V01','11/23/2023', '12/8/2023','0');
END;

-- INSERT_UPDATE_P_TIME_SHEET
-- table: WORKING_PROFILE_DETAIL
BEGIN
    INSERT_UPDATE_P_TIME_SHEET('11/23/2023','12/8/2023');
END;

-- INSERT_UPDATE_P_TIME_SHEET_DETAIL
-- table: WORKING_PROFILE_DETAIL
BEGIN
    INSERT_UPDATE_P_TIME_SHEET_DETAIL('11/23/2023','12/8/2023');
END;

-- > GET TIMESHEET
