-- Table: EMP_EDUCATION
-- ID	NUMBER(10,0)
-- EMPLOYEE_ID	NUMBER(10,0)
-- TYPE	NVARCHAR2(100 CHAR)
-- LEVEL_OF_EDU	NVARCHAR2(50 CHAR)
-- MAJOR	NVARCHAR2(100 CHAR)
-- PLACE	NVARCHAR2(500 CHAR)
-- GRADUATED_DATE	DATE
-- ATTACH_FILE	NVARCHAR2(100 CHAR)
-- IS_DEL	NUMBER(2,0)
-- EXPIRATION_DATE	DATE
-- EFFECTIVE_DATE	DATE
-- CERTIFICATE_NAME	NVARCHAR2(100 CHAR)
-- EMPLOYEE_CODE	NVARCHAR2(100 CHAR)
-- PRIMARY_EDUCATION	NUMBER(1,0)
-- ATTACH_NAME	VARCHAR2(1000 CHAR)
-- REC_ID	NVARCHAR2(50 CHAR)
-- DISCIPLINE_ID	NVARCHAR2(30 CHAR)
-- INSTITUTION_ID	NVARCHAR2(10 CHAR)
-- ATTACH_URL	VARCHAR2(1500 CHAR)
-- TEMP_ID	NUMBER(10,0)

-- Table: TEMP_UPLOAD
-- ID	NUMBER(10,0)
-- TABLE_NAME	NVARCHAR2(30 CHAR)
-- TEMP_ID	NUMBER(10,0)
-- ATTACHMENT_URL	VARCHAR2(2000 CHAR)
-- ATTACHMENT_NAME	VARCHAR2(1000 CHAR)

-- Create a trigger when a new row is inserted into EMP_EDUCATION table, if there is a record in TEMP_UPLOAD table with the same TEMP_ID, then update the ATTACH_URL and ATTACH_NAME in EMP_EDUCATION table with the values from TEMP_UPLOAD table.
-- The TEMP_ID is the primary key of TEMP_UPLOAD table, and it is also the foreign key of EMP_EDUCATION table.

CREATE OR REPLACE TRIGGER TRG_EMP_EDUCATION
AFTER INSERT ON EMP_EDUCATION
FOR EACH ROW
BEGIN
    UPDATE EMP_EDUCATION
    SET ATTACH_URL = (SELECT ATTACHMENT_URL FROM TEMP_UPLOAD WHERE TEMP_ID = :NEW.TEMP_ID),
        ATTACH_NAME = (SELECT ATTACHMENT_NAME FROM TEMP_UPLOAD WHERE TEMP_ID = :NEW.TEMP_ID)
    WHERE TEMP_ID = :NEW.TEMP_ID;
END;
```

-- error ORA-04091: table WKSP_ERP.EMP_EDUCATION is mutating, trigger/function may not see it 

-- Solution: use compound trigger

```sql
CREATE OR REPLACE TRIGGER TRG_EMP_EDUCATION
FOR INSERT ON EMP_EDUCATION
COMPOUND TRIGGER
    TYPE T_TEMP_UPLOAD IS TABLE OF TEMP_UPLOAD%ROWTYPE;
    V_TEMP_UPLOAD T_TEMP_UPLOAD;
    V_TEMP_ID EMP_EDUCATION.TEMP_ID%TYPE;
    V_ATTACH_URL EMP_EDUCATION.ATTACH_URL%TYPE;
    V_ATTACH_NAME EMP_EDUCATION.ATTACH_NAME%TYPE;
    AFTER EACH ROW IS
    BEGIN
        V_TEMP_ID := :NEW.TEMP_ID;
        SELECT ATTACHMENT_URL, ATTACHMENT_NAME
        BULK COLLECT INTO V_TEMP_UPLOAD
        FROM TEMP_UPLOAD
        WHERE TEMP_ID = V_TEMP_ID;
        FOR I IN 1..V_TEMP_UPLOAD.COUNT LOOP
            V_ATTACH_URL := V_TEMP_UPLOAD(I).ATTACHMENT_URL;
            V_ATTACH_NAME := V_TEMP_UPLOAD(I).ATTACHMENT_NAME;
        END LOOP;
        UPDATE EMP_EDUCATION
        SET ATTACH_URL = V_ATTACH_URL,
            ATTACH_NAME = V_ATTACH_NAME
        WHERE TEMP_ID = V_TEMP_ID;
    END AFTER EACH ROW;
END;
```
