SELECT FULL_NAME,EMPLOYEE_ID as ID FROM EMPLOYEES WHERE POSITION_ID = (
select MANAGER_POSITION_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = :APP_USER_ID )

SELECT FULL_NAME,EMPLOYEE_ID as ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 
(select MANAGER_ID FROM EMPLOYEES e WHERE e.USER_NAME = :APP_USER_NAME )
