declare
c_date date := to_CHAR(sysdate,'MM/DD/YYYY');
scholarship_request_id number;

discount_rate number;

begin

-- lấy giá trị của discount_rate bằng id
    SELECT DISCOUNT_RATE INTO discount_rate
    FROM COREEDU_PROMOTION
    WHERE :P20002_DISCOUNT_RATE = ID;

-- cập nhật bảng SCHOLARSHIP_REQUEST 
    UPDATE SCHOLARSHIP_REQUEST sr
    SET 
        -- STATUS = 1,
        -- RECIPIENT_TYPE = :P20002_SCHOLARSHIP_RECIPIENT,
        -- PROGRAM = :P20002_PROGRAM,
        -- REQUESTER_CODE = 
        --     CASE 
        --         WHEN :P20002_SCHOLARSHIP_RECIPIENT = 'D' THEN :P20002_REQUEST_NAME
        --         ELSE :P20002_EMPLOYEE_CODE
        --     END,
        -- REQUESTER_DEPARTMENT = :P20002_DEPARTMENT,
        -- REQUESTER_DEPARTMENT_CODE = :P20002_DEPARTMENT_CODE,
        -- REQUESTER_LEVEL = :P20002_LEVEL,
        PARTNER_NAME = :P20002_PARTNER_NAME,
        PARTNER_PHONE = :P20002_PARTNER_PHONE,
        PARTNER_TITLE = :P20002_TITLE,
        PARTNER_DEPARTMENT = :P20002_PARTNER_DEPARTMENT,
        PARTNER_FIELD = :P20002_FIELD,
        PARTNER_WORKPLACE = :P20002_WORKPLACE,
        RECIPIENT_NAME = :P20002_RECIPIENT_NAME,
        RECIPIENT_DOB = :P20002_RECIPIENT_DOB,
        RECIPIENT_PHONE = :P20002_RECIPIENT_PHONE,
        RECIPIENT_RELATIONSHIP = :P20002_RELATIONSHIP,
        RECIPIENT_CAMPUS = :P20002_CAMPUS,
        ATTACH_NAME = :P20002_NAME_FILES,
        ATTACH_FILE = :P20002_URL_FILES,
        RECIPIENT_REPLACEMENT = :P20002_REPLACEMENT,
        RECIPIENT_VOUCHER_CODE_REPLACEMENT = :P20002_VOUCHER_CODE_REPLACEMENT,
        RECIPIENT_EXPIRATION_DATE_REPLACEMENT = :P20002_EXPIRATION_DATE_REPLACEMENT,
        RECIPIENT_NOTE = :P20002_NOTE,
        RECIPIENT_REASON_REQUEST = :P20002_REASON_REQUEST,
        DISCOUNT_RATE = discount_rate,
        VOUCHER_CODE = :P20002_VOUCHER_CODE,
        NUMBER_OF_COURSES = :P20002_NUMBER_OF_COURSES,
        EFFECTIVE_DATE = :P20002_EFFECTIVE_DATE,
        EXPIRATION_DATE = :P20002_EXPIRATION_DATE,
        APPROVED_DATE = :P20002_APPROVED_DATE,
        CREATED_DATE = c_date,
        ID_COREEDU_PROMOTION = :P20002_DISCOUNT_RATE
    WHERE :P20002_REQUEST_ID = sr.ID;

    UPDATE EMP_REQUESTS emp
    SET
        NOTE = 
            CASE 
                WHEN :P20002_SCHOLARSHIP_RECIPIENT = 'A' OR :P20002_SCHOLARSHIP_RECIPIENT = 'B' THEN :P20002_NOTE
                ELSE :P20002_REASON_REQUEST
            END
    WHERE :P20002_REQUEST_ID = emp.REQUEST_DETAIL_ID AND LOWER(:P20002_FEATURE) = LOWER(emp.REQUEST_TYPE);


    -- Insert ATTACHMENT_HISTORY
    -- IF(:P20002_DEFAULT_IMAGES_URL != :P20002_URL_FILES) THEN
    -- Insert ATTACHMENT_HISTORY
    IF(remove_first_semicolon(:P20002_DEFAULT_IMAGES_URL) != :P20002_URL_FILES or
       ( :P20002_REQUEST_ID is null and :P20002_URL_FILES is not null )) 
    THEN
        INSERT INTO ATTACHMENT_HISTORY (ATTACHMENT_DATE, EMPLOYEE_CODE, ATTACHMENT_URL, ATTACHMENT_NAME, REQUEST_ID)
        VALUES(sysdate, :APP_EMP_CODE, :P20002_URL_FILES, :P20002_NAME_FILES, (select ID from EMP_REQUESTS er where :P20002_REQUEST_ID = er.REQUEST_DETAIL_ID));
    END IF;

    -- Write log attachments
    -- INSERT INTO OUTPUT_LOGS(NUMBER1, STR1, STR2, STR3)
    -- VALUES ((select ID from EMP_REQUESTS er where :P20002_REQUEST_ID = er.REQUEST_DETAIL_ID), 'upload_scho', :P20002_DEFAULT_IMAGES_URL, :P20002_URL_FILES);
    
end;