-- DEMO_UPLOAD_FILE
-- ID	NUMBER(3,0)
-- ATTACHMENT_URL	NVARCHAR2(2000 CHAR)
-- ATTACHMENT_NAME	NVARCHAR2(500 CHAR)
DECLARE
count_id NUMBER;

BEGIN
    select count(*) into count_id FROM DEMO_UPLOAD_FILE where ID = :P21_ID;

    -- :P21_ATTACHMENT_NAME
    -- :P21_ATTACHMENT_URL
    IF count_id = 0 THEN
        INSERT INTO DEMO_UPLOAD_FILE (ID, ATTACHMENT_URL, ATTACHMENT_NAME) VALUES (:P21_ID, :P21_ATTACHMENT_URL, :P21_ATTACHMENT_NAME);
    ELSE
        UPDATE DEMO_UPLOAD_FILE SET ATTACHMENT_URL = :P21_ATTACHMENT_URL, ATTACHMENT_NAME = :P21_ATTACHMENT_NAME WHERE ID = :P21_ID;
    END IF;
END;